### ISSUE TITLE
options : redirect_https & sticky_sessions not working 

### ISSUE THREAD

**Issue by davlgd** [CleverCloud/terraform-provider-clevercloud#40]
When I deploy a node/PG application through the provider with some options, they are not applied.

- Terraform version : 1.4.5
- Provider version : 0.0.10

### Terraform Configuration Files
```
provider "clevercloud" {
  organisation = var.organisation
}

resource "clevercloud_postgresql" "terraformTestPG" {
  name = "terraformTestPG"
  plan = "xxs_sml"
  region = "scw"
}

resource "clevercloud_nodejs" "terraformTestApp" {
  name = "terraformTestApp"
  region = "scw"
  min_instance_count = 1
  max_instance_count = 4
  smallest_flavor = "nano"
  biggest_flavor = "XS"
  redirect_https = true
  sticky_sessions = true
  additional_vhosts = ["demotf.dauh.fr"]
  dependencies = [clevercloud_postgresql.terraformTestPG.id]
  deployment {repository = "https://github.com/CleverCloud/expressjs-postgresql-example"}
}
```

### Expected Behavior
Enabling `redirect_https` or `sticky_sessions` should activate these options in the deployed application.

### Actual Behavior
When set to `true`, `redirect_https` or `sticky_sessions` stay disabled in the deployed application.

### Steps to Reproduce

- Use this config in a main.tf file
- `terraform apply`
- Look at the Clever Cloud Console nodejs app in the Information panel
- HTTPS/Sticky options are not activated

**Comment by miton18** [comment]
Closed by #43
