### ISSUE TITLE
Pushing a custom branch fails

### ISSUE THREAD

**Issue by Falinor** [CleverCloud/terraform-provider-clevercloud#96]
Hi there,

Pushing a custom branch, for instance `main`, fails.
CleverCloud enforces the use of a `master` branch on its git repositories, which is a limitation.
Like pushing manually using `git push clever main:master`, it should be possible to deploy a custom branch using Terraform.

### Terraform Version
```shell
$ terraform -v
Terraform v1.10.3
on darwin_arm64
provider registry.terraform.io/clevercloud/clevercloud v0.5.0
```

### Affected Resource(s)
- clevercloud_nodejs (and anything git-related)

### Terraform Configuration Files
```tf
resource "clevercloud_nodejs" "api" {
  name               = "terraform-test"
  region             = var.region
  build_flavor       = "M"
  min_instance_count = 1
  max_instance_count = 1
  smallest_flavor    = "XS"
  biggest_flavor     = "XS"

  package_manager = "npm"

  deployment {
    repository = "https://github.com/Falinor/clevercloud-terraform-provider-issue"
    commit     = "main"
  }
}
```

A reproduction repository is available [there](https://github.com/Falinor/clevercloud-terraform-provider-issue).

### Debug Output
https://gist.github.com/Falinor/944a327da412faaeabe86310830e1762

### Expected Behavior
CleverCloud should retrieve a custom branch (for instance `main`) on its `master` branch.

### Actual Behavior
CleverCloud declined the branch `main` to be pushed to the repository.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Important Factoids
None

### References
My reproduction repository [there](https://github.com/Falinor/clevercloud-terraform-provider-issue) to help.

**Comment by miton18** [comment]
First, thanks for this perfect bug report, I will work on it soon

**Comment by miton18** [comment]
@Falinor can you test v0.5.1 ?

**Comment by Falinor** [comment]
I can confirm that pushing `main` or another branch is now working 😄 
Thanks a lot!
